# .github/workflows/build.yml
name: Build installers
on: [workflow_dispatch]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - run: pip install pyinstaller
      - run: pip install .
      - run: pyinstaller --noconfirm --onefile --windowed src/hotkey_transcriber/main.py
      - uses: actions/upload-artifact@v4
        with: {name: hotkey-transcriber-win, path: dist/main.exe}
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - run: pip install briefcase
      - run: briefcase create linux && briefcase build linux && briefcase package linux
      - uses: actions/upload-artifact@v4
        with: {name: hotkey-transcriber-linux, path: dist/linux/*}
