# .github/workflows/build.yml
name: Build Packages
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - run: pip install pyinstaller
      - run: pip install .
      - run: pyinstaller --noconfirm --onefile --windowed --paths src src/hotkey_transcriber/main.py
      - uses: actions/upload-artifact@v4
        with: {name: hotkey-transcriber-win, path: dist/*.exe}
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .
      - run: pyinstaller --noconfirm --onefile src/hotkey_transcriber/main.py --name hotkey-transcriber
      - run: |
          mkdir -p AppDir/usr/bin
          cp dist/hotkey-transcriber AppDir/usr/bin/
          cp src/hotkey_transcriber/resources/icon/microphone.png AppDir/
          cp desktop_files/linux/hotkey-transcriber.desktop AppDir/
      - run: ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
      - uses: actions/upload-artifact@v4
        with: {name: hotkey-transcriber-linux, path: dist/linux/*}
