name: Translate README
on:
  push:
    paths:
      - README.de.md
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:            # <-- wichtig fürs Commit!
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Translate DE -> en-US
        uses: lyqht/deepl-translate-github-action@v2.1.1
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          target_languages: en-US                # DeepL-Code, kleingeschrieben
          input_file_path: README.de.md
          output_file_name_pattern: README.md # überschreibt/erstellt README.md

      - name: Commit and push if changed
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "Auto-translated README → English"
            git push
          else
            echo "Nothing to commit"
          fi
